services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: dev
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: yarn dev --host
