services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: prod

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: prod
      args:
        VITE_API_BASE_URL: "http://localhost:8000"
